/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author pedro
 */
public class MostrarPartida extends javax.swing.JFrame {

    /**
     * Creates new form Partida
     */
    public MostrarPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEquipe1 = new javax.swing.JPanel();
        lblEquipe1 = new javax.swing.JLabel();
        scrJogEquipe1 = new javax.swing.JScrollPane();
        lstJogEquipe1 = new javax.swing.JList<>();
        lblJogadoresEquipe1 = new javax.swing.JLabel();
        scrPersonagensEquipe1 = new javax.swing.JScrollPane();
        lstPersonagensEquipe1 = new javax.swing.JList<>();
        lblPersonagensEquipe1 = new javax.swing.JLabel();
        pnlEquipe2 = new javax.swing.JPanel();
        lblEquipe2 = new javax.swing.JLabel();
        scrJogEquipe2 = new javax.swing.JScrollPane();
        lstJogEquipe2 = new javax.swing.JList<>();
        lblJogadoresEquipe2 = new javax.swing.JLabel();
        scrPersonagensEquipe2 = new javax.swing.JScrollPane();
        lstPersonagensEquipe2 = new javax.swing.JList<>();
        lblPersonagensEquipe2 = new javax.swing.JLabel();
        lblResultParcial = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        lblVitEquipe1 = new javax.swing.JLabel();
        lblVitEquipe2 = new javax.swing.JLabel();
        sprLinha1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResultados = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlEquipe1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEquipe1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEquipe1.setText("Equipe 1");

        lstJogEquipe1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Jogador1Equipe1", "Jogador2Equipe1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrJogEquipe1.setViewportView(lstJogEquipe1);

        lblJogadoresEquipe1.setText("Jogadores:");

        lstPersonagensEquipe1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BulbAssalto", "PikaChurros" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrPersonagensEquipe1.setViewportView(lstPersonagensEquipe1);

        lblPersonagensEquipe1.setText("Personagens:");

        javax.swing.GroupLayout pnlEquipe1Layout = new javax.swing.GroupLayout(pnlEquipe1);
        pnlEquipe1.setLayout(pnlEquipe1Layout);
        pnlEquipe1Layout.setHorizontalGroup(
            pnlEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipe1Layout.createSequentialGroup()
                .addGroup(pnlEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEquipe1Layout.createSequentialGroup()
                        .addGroup(pnlEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEquipe1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEquipe1Layout.createSequentialGroup()
                                .addComponent(lblJogadoresEquipe1)
                                .addGap(68, 68, 68)
                                .addComponent(lblPersonagensEquipe1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlEquipe1Layout.createSequentialGroup()
                        .addComponent(scrJogEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrPersonagensEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlEquipe1Layout.setVerticalGroup(
            pnlEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipe1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEquipe1)
                .addGap(18, 18, 18)
                .addGroup(pnlEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJogadoresEquipe1)
                    .addComponent(lblPersonagensEquipe1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEquipe1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrPersonagensEquipe1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(scrJogEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlEquipe2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEquipe2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEquipe2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEquipe2.setText("Equipe 2");

        lstJogEquipe2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Jogador1Equipe2", "Jogador2Equipe2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrJogEquipe2.setViewportView(lstJogEquipe2);

        lblJogadoresEquipe2.setText("Jogadores:");

        lstPersonagensEquipe2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "BulbAssalto", "PikaChurros" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrPersonagensEquipe2.setViewportView(lstPersonagensEquipe2);

        lblPersonagensEquipe2.setText("Personagens:");

        javax.swing.GroupLayout pnlEquipe2Layout = new javax.swing.GroupLayout(pnlEquipe2);
        pnlEquipe2.setLayout(pnlEquipe2Layout);
        pnlEquipe2Layout.setHorizontalGroup(
            pnlEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipe2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquipe2Layout.createSequentialGroup()
                        .addComponent(scrJogEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrPersonagensEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquipe2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquipe2Layout.createSequentialGroup()
                                .addComponent(lblPersonagensEquipe2)
                                .addGap(56, 56, 56)
                                .addComponent(lblJogadoresEquipe2))
                            .addComponent(lblEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlEquipe2Layout.setVerticalGroup(
            pnlEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEquipe2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEquipe2)
                .addGap(18, 18, 18)
                .addGroup(pnlEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJogadoresEquipe2)
                    .addComponent(lblPersonagensEquipe2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEquipe2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrPersonagensEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrJogEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblResultParcial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResultParcial.setText("Resultados Parciais");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit32px.png"))); // NOI18N
        btnSair.setText("Sair");

        lblVitEquipe1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVitEquipe1.setText("Vitória Equipe 2!!");

        lblVitEquipe2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVitEquipe2.setText("Vitória Equipe 1!!");

        txaResultados.setColumns(20);
        txaResultados.setRows(5);
        jScrollPane1.setViewportView(txaResultados);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stats_15267.png"))); // NOI18N
        jButton1.setText("Reportar Resultados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEquipe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEquipe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sprLinha1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblVitEquipe2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblVitEquipe1))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(lblResultParcial)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlEquipe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEquipe2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResultParcial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVitEquipe1)
                            .addComponent(lblVitEquipe2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sprLinha1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEquipe1;
    private javax.swing.JLabel lblEquipe2;
    private javax.swing.JLabel lblJogadoresEquipe1;
    private javax.swing.JLabel lblJogadoresEquipe2;
    private javax.swing.JLabel lblPersonagensEquipe1;
    private javax.swing.JLabel lblPersonagensEquipe2;
    private javax.swing.JLabel lblResultParcial;
    private javax.swing.JLabel lblVitEquipe1;
    private javax.swing.JLabel lblVitEquipe2;
    private javax.swing.JList<String> lstJogEquipe1;
    private javax.swing.JList<String> lstJogEquipe2;
    private javax.swing.JList<String> lstPersonagensEquipe1;
    private javax.swing.JList<String> lstPersonagensEquipe2;
    private javax.swing.JPanel pnlEquipe1;
    private javax.swing.JPanel pnlEquipe2;
    private javax.swing.JScrollPane scrJogEquipe1;
    private javax.swing.JScrollPane scrJogEquipe2;
    private javax.swing.JScrollPane scrPersonagensEquipe1;
    private javax.swing.JScrollPane scrPersonagensEquipe2;
    private javax.swing.JSeparator sprLinha1;
    private javax.swing.JTextArea txaResultados;
    // End of variables declaration//GEN-END:variables
}
