package telas;

import classes.Avaliacao;
import classes.Organizador;
import classes.Jogador;
import classes.Partida;
import classes.Torneio;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

public class MostrarTorneio extends javax.swing.JFrame {
    
    private Torneio torneioAtual;
    private Avaliacao avaliacaoUsuario;
    
    public MostrarTorneio() {
        initComponents();
        
        torneioAtual = BuscaTorneios.torneioSelecionado;
        
        // Coloca os dados do torneio nos campos de texto
        this.setTitle(torneioAtual.getNome());
        lblNomeTorneio.setText(torneioAtual.getNome());
        txtNumEquipes.setText("" + torneioAtual.getNumeroDeEquipes());      // transforma int em string
        frmData.setText(formatarData(torneioAtual.getDataDeRealizacao()));
        if (torneioAtual.isAtivo()) {
            txtVencedor.setText("A Definir");
            lblAcontecendo.setVisible(true);
            
            btnAvaliacao.setEnabled(false);
            btnAvaliacao.setVisible(false);
        } else {
            txtVencedor.setText(torneioAtual.vencedor().getNome());
            lblAcontecendo.setVisible(false);
            btnAvaliacao.setEnabled(true);
        }
        txtJogo.setText(torneioAtual.getJogo().getNome());
        
        montarTabelas(true, true);
        
        setTxtFields(false);
        
        if (Login.usuarioLogado instanceof Organizador) {
            btnInscricaoEdicao.setText("Editar");
            btnInscricaoEdicao.setEnabled(true);
            
            btnAvaliacao.setEnabled(false);
            btnAvaliacao.setVisible(false);
        } else {
            // Logica pra ver se o usuario ja ta inscrito no torneio
        }
    
    }
    
    // formata o toString do date pra uma string que colocamos no fmrData
    private String formatarData(Date data) {
        DateFormat formatador = new SimpleDateFormat("ddMMyyyy");
        String quando = formatador.format(data);
        return quando;
    }
    
    // monta as tabelas, se eh pra montar passa o argumento como true
    private void montarTabelas(boolean tabelaEquipe, boolean tabelaPartida) {
        if (tabelaEquipe) {
            ArrayList<Avaliacao> listaAva = torneioAtual.getAvaliacoes();
            DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Equipe"}, 0);

            for (int i = 0 ; i < listaAva.size() ; i++) {
                Object linha[] = {listaAva.get(i).getEquipe().getNome()};
                modelo.addRow(linha);
            }

            tblEquipes.setModel(modelo);

            tblEquipes.getColumnModel().getColumn(0).setPreferredWidth(50);
        }
        if (tabelaPartida) {
            ArrayList<Partida> listaPartidas = torneioAtual.getPartidas();
            DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Equipe 1", "Equipe 2", "Vencedor"}, 0);

            for (int i = 0 ; i < listaPartidas.size() ; i++) {
                Object linha[] = {listaPartidas.get(i).getEquipe1().getNome(), 
                                  listaPartidas.get(i).getEquipe2().getNome(), 
                                  listaPartidas.get(i).getVencedor().getNome()};
                modelo.addRow(linha);
            }

            tblPartidas.setModel(modelo);

            tblPartidas.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblPartidas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblPartidas.getColumnModel().getColumn(2).setPreferredWidth(50);
        }
    }
    
    private void setTxtFields (boolean estado) {
        txtJogo.setEnabled(estado);
        txtNumEquipes.setEnabled(estado);
        txtVencedor.setEnabled(estado);
        frmData.setEnabled(estado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeTorneio = new javax.swing.JLabel();
        sprLinha = new javax.swing.JSeparator();
        scrEquipes = new javax.swing.JScrollPane();
        tblEquipes = new javax.swing.JTable();
        lblNumEquipes = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        sprSair = new javax.swing.JSeparator();
        btnSair = new javax.swing.JButton();
        lblVencedor = new javax.swing.JLabel();
        scrPartidas = new javax.swing.JScrollPane();
        tblPartidas = new javax.swing.JTable();
        txtNumEquipes = new javax.swing.JTextField();
        frmData = new javax.swing.JFormattedTextField();
        btnAvaliacao = new javax.swing.JButton();
        btnInscricaoEdicao = new javax.swing.JButton();
        txtVencedor = new javax.swing.JTextField();
        lblJogo = new javax.swing.JLabel();
        txtJogo = new javax.swing.JTextField();
        lblAcontecendo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Torneio");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/trofeu32px.png")).getImage());

        lblNomeTorneio.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNomeTorneio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/trofeu32px.png"))); // NOI18N
        lblNomeTorneio.setText("Nome");

        tblEquipes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrEquipes.setViewportView(tblEquipes);

        lblNumEquipes.setText("Número de Equipes:");

        lblData.setText("Data:");

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit32px.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        lblVencedor.setText("Equipe Vencedora:");

        tblPartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Equipe 1", "Equipe 2", "Vencedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrPartidas.setViewportView(tblPartidas);

        try {
            frmData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAvaliacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/avaliacao32px.png"))); // NOI18N
        btnAvaliacao.setText("Avaliação");

        btnInscricaoEdicao.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnInscricaoEdicao.setText("Inscreva-se!");
        btnInscricaoEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscricaoEdicaoActionPerformed(evt);
            }
        });

        lblJogo.setText("Jogo:");

        lblAcontecendo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAcontecendo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcontecendo.setText("Em Andamento!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sprLinha, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(sprSair, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeTorneio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblVencedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVencedor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumEquipes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNumEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblJogo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtJogo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblData)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(frmData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 13, Short.MAX_VALUE))
                            .addComponent(lblAcontecendo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAvaliacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInscricaoEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNomeTorneio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumEquipes)
                            .addComponent(txtNumEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblData)
                            .addComponent(frmData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVencedor)
                            .addComponent(txtVencedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJogo)
                            .addComponent(txtJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAcontecendo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scrPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(scrEquipes, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sprSair, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInscricaoEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnAvaliacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscricaoEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscricaoEdicaoActionPerformed
        new InscricaoEquipe().setVisible(true);
    }//GEN-LAST:event_btnInscricaoEdicaoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new BuscaTorneios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarTorneio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarTorneio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacao;
    private javax.swing.JButton btnInscricaoEdicao;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField frmData;
    private javax.swing.JLabel lblAcontecendo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblJogo;
    private javax.swing.JLabel lblNomeTorneio;
    private javax.swing.JLabel lblNumEquipes;
    private javax.swing.JLabel lblVencedor;
    private javax.swing.JScrollPane scrEquipes;
    private javax.swing.JScrollPane scrPartidas;
    private javax.swing.JSeparator sprLinha;
    private javax.swing.JSeparator sprSair;
    private javax.swing.JTable tblEquipes;
    private javax.swing.JTable tblPartidas;
    private javax.swing.JTextField txtJogo;
    private javax.swing.JTextField txtNumEquipes;
    private javax.swing.JTextField txtVencedor;
    // End of variables declaration//GEN-END:variables

}
